#!/usr/bin/env python3
"""Regenerate internal/compose/prices_table.go from AWS's published price
lists (no credentials): the EC2 on-demand Linux list price per hour of every
size of the four GPU families cluster-manager composes pools from (g6, g5,
g4dn, g6e), and the EBS gp3 list prices a model cache claim is billed at —
storage per GiB-month, provisioned throughput per MiB/s-month above the
tier's 125 MiB/s, provisioned IOPS per IOPS-month above its 3000 — for the
regions the fleet runs in. Run it, review the diff, commit it; the table's
date is the run's."""
import datetime
import gzip
import json
import subprocess
import sys
import urllib.parse
import urllib.request

FAMILIES = ("g6", "g5", "g4dn", "g6e")
# AWS region code -> the location name AWS's price list files it under.
REGIONS = {
    "eu-central-1": "EU (Frankfurt)",
    "eu-west-1": "EU (Ireland)",
    "eu-west-2": "EU (London)",
    "eu-north-1": "EU (Stockholm)",
    "us-east-1": "US East (N. Virginia)",
    "us-west-2": "US West (Oregon)",
    "ap-southeast-1": "Asia Pacific (Singapore)",
}
URL = ("https://b0.p.awsstatic.com/pricing/2.0/meteredUnitMaps/ec2/USD/current/"
       "ec2-ondemand-without-sec-sel/%s/Linux/index.json")
# The EBS list, every location in one file; the gp3 rows by AWS's names.
EBS_URL = "https://b0.p.awsstatic.com/pricing/2.0/meteredUnitMaps/ec2/USD/current/ebs.json"
EBS_GP3 = {
    "storage": "Storage General Purpose gp3 GB Mo",
    "throughput": "Provisioned Throughput gp3 per GiBps mo",
    "iops": "Provisioned EBS IOPS gp3 Volumes per IOPS Mo",
}


def get(url):
    req = urllib.request.Request(url, headers={"Accept-Encoding": "identity"})
    with urllib.request.urlopen(req, timeout=60) as r:
        raw = r.read()
    try:
        return json.loads(raw)
    except ValueError:
        return json.loads(gzip.decompress(raw))


def fetch(location):
    return get(URL % urllib.parse.quote(location))


def figure(price):
    """AWS prints ten decimals; the figure is kept exactly, trailing zeros dropped (1.2224500000 -> 1.22245)."""
    return price.rstrip("0").rstrip(".") if "." in price else price


def ebs_gp3(ebs, location):
    """The gp3 figures of a location: storage per GiB-month, throughput per
    MiB/s-month (AWS lists it per GiB/s-month; divided by 1024 and kept to
    ten decimals), IOPS per IOPS-month — every one required."""
    rows = ebs["regions"][location]
    out = {}
    for key, name in EBS_GP3.items():
        price = rows[name]["price"]
        if key == "throughput":
            price = "%.10f" % (float(price) / 1024)
        out[key] = figure(price)
    return out


def main(out):
    today = datetime.date.today().isoformat()
    lines = [
        "// Code generated by hack/aws-on-demand-prices.py; DO NOT EDIT.",
        "//",
        "// AWS list prices in USD, read on %s from AWS's published price lists" % today,
        "// (b0.p.awsstatic.com/pricing/2.0/meteredUnitMaps/ec2: ec2-ondemand-without-sec-sel",
        "// per location, and ebs.json), for the regions the fleet runs in: the EC2",
        "// on-demand Linux price per hour of every size of the GPU families",
        "// cluster-manager composes pools from — a size AWS does not offer in a",
        "// region has no row — and the EBS gp3 prices a model cache claim is billed",
        "// at. Refresh with `python3 hack/aws-on-demand-prices.py`.",
        "",
        "package compose",
        "",
        "// PriceAsOf is the date the price table was read from AWS.",
        'const PriceAsOf = "%s"' % today,
        "",
        "// regionLocations names each region of the price table as AWS's price list",
        "// does.",
        "var regionLocations = map[string]string{",
    ]
    for code in REGIONS:
        lines.append('\t"%s": "%s",' % (code, REGIONS[code]))
    lines += ["}", "", "// onDemandPrices is USD per hour per instance type, per region.", "var onDemandPrices = map[string]map[string]float64{"]
    for code, location in REGIONS.items():
        data = fetch(location)["regions"][location]
        prices = {}
        for entry in data.values():
            itype = entry["Instance Type"]
            if itype.split(".")[0] in FAMILIES:
                prices[itype] = figure(entry["price"])
        print("%s: %d sizes" % (code, len(prices)), file=sys.stderr)
        lines.append('\t"%s": {' % code)
        for itype in sorted(prices, key=lambda t: (t.split(".")[0], float(prices[t]))):
            lines.append('\t\t"%s": %s,' % (itype, prices[itype]))
        lines.append("\t},")
    lines += ["}", ""]
    ebs = get(EBS_URL)
    lines += [
        "// ebsGP3Prices is what a gp3 volume is billed per month, per region: USD per",
        "// GiB of storage, per MiB/s of provisioned throughput above the tier's",
        "// GP3BaselineThroughputMiBps, per IOPS above its GP3BaselineIOPS.",
        "var ebsGP3Prices = map[string]gp3Price{",
    ]
    for code, location in REGIONS.items():
        p = ebs_gp3(ebs, location)
        print("%s: gp3 storage %s, throughput %s, iops %s" % (code, p["storage"], p["throughput"], p["iops"]), file=sys.stderr)
        lines.append('\t"%s": {storageGiBMonth: %s, throughputMiBpsMonth: %s, iopsMonth: %s},' % (code, p["storage"], p["throughput"], p["iops"]))
    lines += ["}", ""]
    with open(out, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    subprocess.run(["gofmt", "-w", out], check=True)


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "internal/compose/prices_table.go")
