#!/usr/bin/env python3
"""Regenerate internal/compose/prices_table.go from AWS's published EC2
on-demand price list (no credentials): the Linux list price per hour of every
size of the four GPU families cluster-manager composes pools from (g6, g5,
g4dn, g6e), for the regions the fleet runs in. Run it, review the diff, commit
it; the table's date is the run's."""
import datetime
import gzip
import json
import subprocess
import sys
import urllib.parse
import urllib.request

FAMILIES = ("g6", "g5", "g4dn", "g6e")
# AWS region code -> the location name AWS's price list files it under.
REGIONS = {
    "eu-central-1": "EU (Frankfurt)",
    "eu-west-1": "EU (Ireland)",
    "eu-west-2": "EU (London)",
    "eu-north-1": "EU (Stockholm)",
    "us-east-1": "US East (N. Virginia)",
    "us-west-2": "US West (Oregon)",
    "ap-southeast-1": "Asia Pacific (Singapore)",
}
URL = ("https://b0.p.awsstatic.com/pricing/2.0/meteredUnitMaps/ec2/USD/current/"
       "ec2-ondemand-without-sec-sel/%s/Linux/index.json")


def fetch(location):
    req = urllib.request.Request(URL % urllib.parse.quote(location), headers={"Accept-Encoding": "identity"})
    with urllib.request.urlopen(req, timeout=60) as r:
        raw = r.read()
    try:
        return json.loads(raw)
    except ValueError:
        return json.loads(gzip.decompress(raw))


def main(out):
    today = datetime.date.today().isoformat()
    lines = [
        "// Code generated by hack/aws-on-demand-prices.py; DO NOT EDIT.",
        "//",
        "// AWS EC2 on-demand Linux list prices in USD per hour, read on %s from" % today,
        "// AWS's published price list (b0.p.awsstatic.com/pricing/2.0/meteredUnitMaps/ec2,",
        "// ec2-ondemand-without-sec-sel, per location), for the GPU families",
        "// cluster-manager composes pools from and the regions the fleet runs in. A",
        "// size AWS does not offer in a region has no row. Refresh with",
        "// `python3 hack/aws-on-demand-prices.py`.",
        "",
        "package compose",
        "",
        "// PriceAsOf is the date the price table was read from AWS.",
        'const PriceAsOf = "%s"' % today,
        "",
        "// regionLocations names each region of the price table as AWS's price list",
        "// does.",
        "var regionLocations = map[string]string{",
    ]
    for code in REGIONS:
        lines.append('\t"%s": "%s",' % (code, REGIONS[code]))
    lines += ["}", "", "// onDemandPrices is USD per hour per instance type, per region.", "var onDemandPrices = map[string]map[string]float64{"]
    for code, location in REGIONS.items():
        data = fetch(location)["regions"][location]
        prices = {}
        for entry in data.values():
            itype = entry["Instance Type"]
            if itype.split(".")[0] in FAMILIES:
                # AWS prints ten decimals; the figure is kept exactly, trailing
                # zeros dropped (1.2224500000 -> 1.22245).
                prices[itype] = entry["price"].rstrip("0").rstrip(".") if "." in entry["price"] else entry["price"]
        print("%s: %d sizes" % (code, len(prices)), file=sys.stderr)
        lines.append('\t"%s": {' % code)
        for itype in sorted(prices, key=lambda t: (t.split(".")[0], float(prices[t]))):
            lines.append('\t\t"%s": %s,' % (itype, prices[itype]))
        lines.append("\t},")
    lines += ["}", ""]
    with open(out, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    subprocess.run(["gofmt", "-w", out], check=True)


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "internal/compose/prices_table.go")
